dotenv: "{{ playbook_dir + '/docker-config/.env' }}"

shell:    /bin/bash
username: yaneko
password: "{{ lookup('dotenv', 'PASSWORD', file=dotenv) }}"
EMAIL:    "{{ lookup('dotenv', 'EMAIL',    file=dotenv) }}"

HOMEDIR:  "{{ lookup('dotenv', 'HOMEDIR', file=dotenv) }}"
CONFDIR:  "{{ lookup('dotenv', 'CONFDIR', file=dotenv) }}"
BACKDIR:  "{{ lookup('dotenv', 'BACKDIR', file=dotenv) }}"
DATADIR:  "{{ lookup('dotenv', 'DATADIR', file=dotenv) }}"

USERGIT: git@github.com:yan3ku/config.git
USERCONF: "{{ HOMEDIR }}/{{ USERGIT | regex_search('/(.*)\\.git$', '\\1') | first }}"

packages:
  - git
  - git-secret
  - stow
  - emacs
  - tmux
  - xfsprogs
  - mergerfs
  - htop
  - lm-sensors
  - fancontrol
  - msmtp
  - msmtp-mta
  - smartmontools
