---
spearhead:
  hosts:
    yaneko.net:
      ansible_host: 10.10.10.10
      ansible_user: yaneko
      ansible_port: 22

pararaid:
  hosts:
    hetzner:
      ansible_host: 10.10.10.10
      ansible_user: root
      ansible_port: 22
