---
spearhead:
  hosts:
    vm:
      ansible_host: 10.10.10.10
      ansible_user: yaneko
      ansible_port: 22
    yaneko.net:
      ansible_host: 192.168.1.86
      ansible_user: yaneko
      ansible_port: 1234

pararaid:
  hosts:
    vpn_vm:
      ansible_host: 10.10.10.10
      ansible_user: root
      ansible_port: 22
    hetzner:
      ansible_user: yaneko
      ansible_port: 1234
