---
- name: Deploy VPN
  hosts: pararaid
  become: true
  roles:
    - role: user
      vars:
        user_name: yaneko
        user_nopasswd_sudo: true
        user_groups: ['users', 'sudo']
    - role: ssh
      vars:
        ssh_port: 1234
        ssh_user: yaneko
    - role: firewall
      vars:
        lan_nets:
          - 192.168.1.0/24
          - 10.0.0.0/24
    - role: wireguard
      vars:
        wg_subnet: 10.0.0.0/24
    - role: user
      vars:
        user_name: vault
        user_home: /var/vault
