---
- name: Deploy VPN
  hosts: pararaid
  become: true
  vars:
    user_name: yaneko
  roles:
    - role: apt
      packages:
        - tcpdump
    - role: user
      vars:
        user_nopasswd_sudo: true
        user_groups: ['users', 'sudo']
    - role: firewall
      vars:
        lan_nets:
          - 192.168.1.0/24
          - 10.0.0.0/24
    - role: wireguard
      vars:
        wg_subnet: 10.0.0.0/24
    - role: ssh
    - role: sshd                # this permits root login so must be last
