---
- name: Deploy VPN
  hosts: pararaid
  become: true
  vars:
    username: yaneko
    ssh_port: 1234
    shell: /bin/bash
    user_groups: ['users', 'sudo']
    wg_subnet: 10.0.0.0/24
    lan_nets:
      - 192.168.1.0/24
      - 10.0.0.0/24
  roles:
    - role: user
    - role: ssh
    - role: firewall
    - role: wireguard
