---
- name: Setup server
  hosts: all
  become: true
  roles:
    - role: apt
    - role: groups
    - role: networkd
    - role: pool
    - role: smartd
    - role: user
    - role: ssh
    - role: config
    - role: gpg
    - role: samba
    - role: mail
    - role: wireguard
    - role: backup
