---
- name: Setup server
  hosts: all
  become: yes
  tasks:
    - include_tasks: tasks/install-packages.yml
    - include_tasks: tasks/merge-pool.yml
    - include_tasks: tasks/setup-user.yml
    - include_tasks: tasks/restore-backup.yml
    - include_tasks: tasks/setup-cron.yml
