---
- name: Deploy NAS
  hosts: spearhead
  become: true
  vars:
    user_name: yaneko
    lan_nets:
      - 192.168.1.0/24
      - 10.0.0.0/24
  roles:
    - role: ansible
    - role: apt
      vars:
        packages:
          - emacs
          - xfsprogs
          - htop
          - tcpdump
          - lm-sensors
          - fancontrol
    - role: groups
    - role: pool
    - role: mvhome
    - role: user
      vars:
        user_groups: ['users', 'sudo', 'docker']
        user_nopasswd_sudo: true
    # private ssh keys are needed to pull backup
    - role: ssh
      vars:
        user_name: yaneko
        ssh_copy_private_key: true
    - role: ssh
      vars:
        user_name: root
        user_home: /root/
        ssh_copy_private_key: true
    - role: backup  # starts async restic job
    - role: sshd    # hardening ssh
    - role: gpg     # transfer gpg keys to access secrets
    - role: config  # user config
      become: true
      become_user: yaneko
      vars:
        user_git: git@github.com:yan3ku/config.git
    - role: smartd
    - role: firewall
    - role: samba
    - role: mail
    - role: wireguard
      vars:
        wg_subnet: 10.0.0.0/24
    - role: geerlingguy.docker
  tasks:
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Restic status
      ansible.builtin.async_status:
        jid: "{{ restic_sleeper.ansible_job_id }}"
      when: not ansible_check_mode and not compose_file.stat.exists
      register: job_result
      until: job_result.finished
      retries: 1000
      delay: 10
