- name: Ensure github.com is in known_hosts
  known_hosts:
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    path: "{{ HOMEDIR }}/.ssh/known_hosts"
    state: present
  become: no

- name: Clone config repo
  git:
    repo: '{{ USERGIT }}'
    dest: "{{ USERCONF }}"
    version: master
    update: yes
  become: no
  notify:
    - stow config
    - reset files adopted by stow
