- name: Get {{ username }} passwd entry
  ansible.builtin.getent:
    database: passwd
    key: "{{ username }}"
- set_fact:
    user_home: "{{ getent_passwd[username][4] }}"

- name: Move user home directory
  when: user_home != HOMEDIR
  block:
    - name: Create user home directory
      file:
        state: directory
        path: "{{ HOMEDIR }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0755"

    - name: Sync old home to new home
      synchronize:
        src: "/home/{{ username }}/"
        dest: "{{ HOMEDIR }}/"
        archive: yes
      delegate_to: "{{ inventory_hostname }}"

    - name: Replace home path for {{ username }} in /etc/passwd
      replace:
        path: /etc/passwd
        regexp: '/home/{{ username }}'
        replace: '{{ HOMEDIR }}'

    - name: Remove old home directory
      file:
        path: "/home/{{ username }}"
        state: absent

    # changing home directory like this breaks gpg agent
    # reseting connection nor restarting gpg agent fixes this
    # only solution for now that worked is rebooting...
    - name: Reboot the server
      reboot:
        msg: "Reboot initiated by Ansible"
        reboot_timeout: 300

- name: Add user to groups
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    home: "{{ HOMEDIR }}"
    groups: >
      {{ users_map.keys() | list | union([
      'users',
      'sudo'
      ])}}
    append: yes
    shell: "{{ shell }}"
    update_password: on_create
