- name: Export GPG key on control node
  shell: "gpg --batch --export-secret-key --armor {{ username }}"
  register: gpg_key_export
  delegate_to: localhost
  changed_when: false
  become: no

- name: Import private GPG key
  shell:
    cmd: "gpg --batch --import"
  args:
    stdin: "{{ gpg_key_export.stdout }}"
  register: gpg_out
  changed_when: "'imported: 1' in gpg_out.stderr"
  become: "{{ item }}"
  with_items:
   - yes
   - no

- name: Deploy authget
  template:
    src: templates/authget.j2
    dest: /usr/bin/authget
    owner: root
    group: root
    mode: '0755'
