---
- name: Install cron
  package:
    name: cron
    state: present

- name: Ensure cron service is up
  service:
    name: cron
    state: started
    enabled: yes

- name: Add backup job
  cron:
    name: weekly backups
    minute: "0"
    hour: "0"
    day: "*"
    month: "*"
    weekday: "1"
    job: "/opt/docker/docker-backup weekly"
