---
- name: Install samba
  ansible.builtin.package:
    name: samba
    state: present

- name: Template samba
  ansible.builtin.template:
    src: templates/smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: "0664"
  notify: Reload samba

- name: Add user to samba shares
  ansible.builtin.command:
    cmd: "smbpasswd -a {{ username }}"
  args:
    stdin: |
           {{ password }}
           {{ password }}
  register: smbpasswd
  changed_when: "'Added user' in smbpasswd.stdout"

- name: Ensure samba is up
  ansible.builtin.service:
    name: samba
    state: started
    enabled: true
