---
tasks:
  - name: Show the CONFDIR variable
    debug:
      var: CONFDIR

  - name: Ensure the CONFDIR exists
    file:
      path: "{{ CONFDIR }}"
      state: directory
      mode: '0755'

  - name: Resolve the latest backup symlink in BACKDIR
    stat:
      path: "{{ BACKDIR }}/latest"
    register: backup_symlink

  - name: Show resolved symlink path
    debug:
      var: backup_symlink.stat

  - name: Sync the latest backup to CONFDIR
    synchronize:
      src: "{{ backup_symlink.stat.lnk_target }}"
      dest: "{{ CONFDIR }}"
      recursive: yes
      copy_links: yes
