---
- name: Create user
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    home: "{{ user_home_dir }}"
    groups:
      - sudo
      - docker
      - users
    append: yes
    shell: "{{ shell }}"
    update_password: on_create

- name: Allow passwordless sudo
  copy:
    dest: "/etc/sudoers.d/{{ username }}"
    content: "{{ username }} ALL=(ALL) NOPASSWD:ALL\n"
    owner: root
    group: root
    mode: '0440'

- name: Ensure .ssh directory exists
  file:
    path: "{{ user_home_dir }}/.ssh"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0700'

- name: Add SSH public key to authorized_keys
  authorized_key:
    user: yaneko
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    state: present

- name: Copy private SSH key
  copy:
    src: "~/.ssh/id_ed25519"
    dest: "{{ user_home_dir }}/.ssh/id_ed25519"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0600'

- name: Ensure github.com is in known_hosts
  known_hosts:
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    path: "{{ user_home_dir }}/.ssh/known_hosts"
    state: present

- name: Clone config repo
  git:
    repo: '{{ user_conf_repo }}'
    dest: "{{ user_conf_dir }}"
    version: master
    update: yes
  become: yes
  become_user: "{{ username }}"

- name: Run .install script
  command: "{{ user_conf_dir }}/.install"
  args:
    creates: "{{ user_conf_dir }}/.install.done"
  become: yes
  become_user: "{{ username }}"
