---
- name: Ensure {{ CONFDIR }} was already synced
  stat:
    path: "{{ CONFDIR }}/.synced"
  register: was_synced

- name: Restore backup
  when: not was_synced.stat.exists
  block:
    - name: Ensure the CONFDIR exists
      file:
        path: "{{ CONFDIR }}"
        owner: "{{ username }}"
        group: "media"
        state: directory
        mode: '0755'

    - name: Ensure source backup exists
      stat:
        path: "{{ BACKDIR }}/latest"
      register: backup_stat

    - name: Fail if source backup doesn't exist
      fail:
        msg: "The backup source directory does not exist: {{ BACKDIR }}/latest"
      when: not backup_stat.stat.exists

    - name: Sync the latest backup to CONFDIR
      synchronize:
        src: "{{ BACKDIR }}/latest/" # this slash is really important to "unpack" the directory
        dest: "{{ CONFDIR }}"
        archive: yes
        recursive: yes
      delegate_to: "{{ inventory_hostname }}"

    - name: Create synced lock
      file:
        path: "{{ CONFDIR }}/.synced"
        state: touch
        mode: '0622'
        owner: root
        group: root

- name: Include Docker role
  include_role:
    name: geerlingguy.docker
