---
- name: Ensure cron service is up
  service:
    name: cron
    state: started
    enabled: yes

- name: Add backup job
  cron:
    name: weekly backups
    minute:  "0"
    hour:    "0"
    day:     "*"
    month:   "*"
    weekday: "1"
    job: >
      /opt/docker/docker-backup weekly &&
      curl -fsS -m 10 --retry 5 -o /dev/null https://healthchecks.yaneko.net/ping/a745bb9c-d71d-49b1-a21d-a916e0bb5dd3
