- name: Preconf postfix name
  debconf:
    name: postfix
    question: postfix/mailname
    value: "yaneko.net"
    vtype: string
  notify: reconfigure postfix

- name: Preconf postfix type
  ansible.builtin.debconf:
    name: postfix
    question: postfix/main_mailer_type
    value: "Internet Site"
    vtype: string
  notify: reconfigure postfix

- name: Set postfix relayhost
  debconf:
    name: postfix
    question: postfix/relayhost
    value: "[smtp.gmail.com]:587"
    vtype: string
  notify: reconfigure postfix

- name: Set postfix protocols
  debconf:
    name: postfix
    question: postfix/protocols
    value: "ipv4"
    vtype: string
  notify: reconfigure postfix

- name: Flush handlers
  meta: flush_handlers

- name: Set Postfix configuration parameters
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: "^{{ item.key }}"
    line: "{{ item.key }} = {{ item.value }}"
    state: present
  loop:
    - { key: "smtp_sasl_auth_enable",      value: "yes" }
    - { key: "smtp_sasl_password_maps",    value: "hash:/etc/postfix/sasl/passwd" }
    - { key: "smtp_sasl_security_options", value: "noanonymous" }
  notify: reload postfix

- name: Deploy passwd
  template:
    src: templates/passwd.j2
    dest: /etc/postfix/sasl/passwd
    owner: root
    group: root
    mode: '0600'
  notify: postmap
