---
- name: Get TANK disk labels
  command: lsblk -o label
  register: lsblk_output
  changed_when: false

- name: Extract tank numbers
  set_fact:
    tank_numbers: "{{ lsblk_output.stdout_lines
    | select('match', '^TANK[0-9]+$')
    | map('regex_replace', '^TANK', '')
    | list }}"

- name: Extracted tank numbers
  debug:
    var: tank_numbers

- name: Create mount points for external storage
  file:
    path: "/mnt/tank{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "media"
    mode: '0755'
  loop: "{{ tank_numbers }}"

- name: Ensure mergerfs mount point exists
  file:
    path: "/mnt/pool"
    state: directory
    owner: "{{ username }}"
    group: "media"
    mode: '0755'

- name: Mount each disk and add to fstab
  mount:
    path: "/mnt/tank{{ item }}"
    src: "LABEL=TANK{{ item }}"
    fstype: xfs
    opts: defaults,noatime,nofail
    state: mounted
  loop:  "{{ tank_numbers }}"

- name: Mount mergerfs pool
  mount:
    path: "/mnt/pool"
    src: "/mnt/tank*"
    fstype: mergerfs
    opts: allow_other,use_ino,cache.files=partial,dropcacheonclose=true,category.create=mfs
    state: mounted
