- name: Create vault user
  ansible.builtin.user:
    name: vault
    shell: "{{ shell }}"
    password: "{{ password | password_hash('sha512') }}"
    create_home: true
    update_password: on_create
    home: /var/vault

- name: Add SSH public key to authorized_keys
  ansible.posix.authorized_key:
    user: vault
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    state: present
