---
- name: Install postfix packages
  ansible.builtin.package:
    name:
      - spamassassin
      - postfix
      - libsasl2-modules
      - postfix-policyd-spf-python
    state: present

- name: Template postfix
  ansible.builtin.template:
    src: templates/{{ item }}
    dest: /etc/postfix/{{ item }}
    owner: root
    group: root
    mode: "0644"
  with_items:
    - main.cf
    - master.cf
    - login_maps.pcre
  notify:
    - Reload postfix
    - Verify email

- name: Postmap sender_relay
  ansible.builtin.template:
    src: templates/sender_relay
    dest: /etc/postfix/sender_relay
    owner: root
    group: root
    mode: "0644"
  notify: Postmap sender_relay

- name: Template sasl passwd
  ansible.builtin.template:
    src: templates/passwd
    dest: /etc/postfix/sasl/passwd
    owner: root
    group: root
    mode: '0600'
  notify: Postmap passwd

- name: Add mail alias from root to {{ username }}
  ansible.builtin.lineinfile:
    path: /etc/aliases
    regexp: "^root"
    line: "root: {{ username }}"
    mode: '0644'
    create: true
  notify: Rebuild aliases

- name: Ensure postfix is up
  ansible.builtin.service:
    name: postfix
    state: started
    enabled: true
