#!/bin/sh
echo -n '{'
first=1
grep -E '^[A-Z0-9_]+_U=' "./docker-config/.env" | while read -r line; do
    key=$(echo "$line" | cut -d= -f1 | sed 's/_U$//' | tr '[:upper:]' '[:lower:]')
    value=$(echo "$line" | cut -d= -f2 | tr -d '[:space:]')
    [ "$first" -eq 1 ] && first=0 || echo -n ', '
    echo -n "\"$key\": $value"
done
echo '}'
