---
- name: Postmap passwd
  ansible.builtin.command: postmap /etc/postfix/sasl/passwd
  changed_when: true

- name: Postmap sender_relay
  ansible.builtin.command: postmap /etc/postfix/sender_relay
  changed_when: true

- name: Rebuild aliases
  ansible.builtin.command: newaliases
  changed_when: true

- name: Restart opendkim
  ansible.builtin.service:
    name: opendkim
    state: restarted

- name: Reload postfix
  ansible.builtin.service:
    name: postfix
    state: reloaded

- name: Verify email
  community.general.mail:
    to: "check-auth-{{ EMAIL | replace('@', '=') }}@verifier.port25.com"
    subject: "Verifier Port 25 Test"
    from: "root@{{ DOMAIN }}"
    body: ""
    charset: "utf-8"
